// Code generated by command: go run asm.go -out out/aegis_amd64.s -stubs out/stub_amd64.go -pkg aegis. DO NOT EDIT.

//go:build gc && !purego
// +build gc,!purego

package aegis

//go:noescape
func aesRoundAsm(out *[16]byte, in *[16]byte, rk *[16]byte)

//go:noescape
func seal128LAsm(key *[16]byte, nonce *[16]byte, out []byte, plaintext []byte, additionalData []byte)

//go:noescape
func open128LAsm(key *[16]byte, nonce *[16]byte, out []byte, ciphertext []byte, tag []byte, additionalData []byte) (ok bool)

//go:noescape
func update128LAsm(s *state128L, m *[32]byte)

//go:noescape
func seal256Asm(key *[32]byte, nonce *[32]byte, out []byte, plaintext []byte, additionalData []byte)

//go:noescape
func open256Asm(key *[32]byte, nonce *[32]byte, out []byte, ciphertext []byte, tag []byte, additionalData []byte) (ok bool)

//go:noescape
func update256Asm(s *state256, m *[16]byte)
